//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaOtomasyon.DAL.SinemaContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiletSatis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BiletSatis()
        {
            this.Fatura = new HashSet<Fatura>();
        }
    
        public int BiletID { get; set; }
        public decimal BiletFiyat { get; set; }
        public bool Satıldı { get; set; }
        public int SeyirciID { get; set; }
        public int GiseID { get; set; }
        public int BiletTurID { get; set; }
        public int FilmID { get; set; }
    
        public virtual BiletTuru BiletTuru { get; set; }
        public virtual Gise Gise { get; set; }
        public virtual Seyirci Seyirci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Fatura { get; set; }
    }
}
