//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaOtomasyon.DAL.SinemaContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int FaturaID { get; set; }
        public int PersoneID { get; set; }
        public int OdemeSekliID { get; set; }
        public int BiletID { get; set; }
        public System.DateTime FaturaTarih { get; set; }
    
        public virtual BiletSatis BiletSatis { get; set; }
        public virtual OdemeSekli OdemeSekli { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
