//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaOtomasyon.DAL.SinemaContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmID { get; set; }
        public string FilmAd { get; set; }
        public string Yonetmen { get; set; }
        public string Oyuncular { get; set; }
        public System.DateTime VizyonGrsTarih { get; set; }
        public System.DateTime VizyonCksTarih { get; set; }
        public string FilmSuresi_dk { get; set; }
        public bool Vizyonda { get; set; }
        public int FilmTurID { get; set; }
        public string Afis { get; set; }
        public int SalonID { get; set; }
    
        public virtual FilmTuru FilmTuru { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
